# data = {}
# responseSession = obj.generateSession(CLIENT_ID,MPIN,totp)
# print("responseSession",responseSession)
# globals().update(responseSession)

# responseSessionKEY = ['broker','clientcode','email','jwtToken','lastlogintime','mobileno','name','products','refreshToken']
# if status:
#   responseSession = data
#   broker = data['broker']
#   clientcode = data['clientcode']
#   email = data['email']
#   jwtToken = data['jwtToken']
#   lastlogintime = data['lastlogintime']
#   mobileno = data['mobileno']
#   name = data['name']
#   products = data['products']
#   refreshToken = data['refreshToken']
#   print(data)
