import os
from datetime import date

def TODAYDATE_IN_TOKEN_FORMAT_STR_UPPER():
    today = date.today()
    TODAYDATE_IN_TOKEN_FORMAT = today.strftime('%d%b%Y')
    return str(TODAYDATE_IN_TOKEN_FORMAT).upper()


current_path = os.getcwd()

TODAYDATE_IN_TOKEN_FORMAT_STR_UPPERs = TODAYDATE_IN_TOKEN_FORMAT_STR_UPPER()

CURRENT_JSON_RES_BANKNIFTY_PATH = os.path.join(current_path, 'DATA','ANGEL_BANKNIFTY_TOKENID')
FUT_ANGEL_BANKNIFTY_TOKENID_PATH = os.path.join(current_path, 'DATA','ANGEL_BANKNIFTY_TOKENID','FUTURE')
CE_ANGEL_BANKNIFTY_TOKENID_PATH = os.path.join(current_path, 'DATA','ANGEL_BANKNIFTY_TOKENID','CE')
PE_ANGEL_BANKNIFTY_TOKENID_PATH = os.path.join(current_path, 'DATA','ANGEL_BANKNIFTY_TOKENID','PE')

FILE_NAME_TOKEN_LIST = TODAYDATE_IN_TOKEN_FORMAT_STR_UPPERs +'.csv'
JSON_FILE_NAME_TOKEN_LIST = TODAYDATE_IN_TOKEN_FORMAT_STR_UPPERs +'.json'
CURRENT_JSON_RES_BANKNIFTY_FILEPATH = os.path.join(CURRENT_JSON_RES_BANKNIFTY_PATH,JSON_FILE_NAME_TOKEN_LIST)
FUT_ANGEL_BANKNIFTY_TOKENID_FILEPATH = os.path.join(FUT_ANGEL_BANKNIFTY_TOKENID_PATH,FILE_NAME_TOKEN_LIST)
CE_ANGEL_BANKNIFTY_TOKENID_FILEPATH = os.path.join(CE_ANGEL_BANKNIFTY_TOKENID_PATH,FILE_NAME_TOKEN_LIST)
PE_ANGEL_BANKNIFTY_TOKENID_FILEPATH = os.path.join(PE_ANGEL_BANKNIFTY_TOKENID_PATH,FILE_NAME_TOKEN_LIST)