
E1 = "ERROR:current_expiry_date key not found in NSE_DATA_DICT"
E2 = "ERROR:Last_price key not found in NSE_DATA_DICT"
E2 = "ERROR:NSE_DATA_DICT IS empty return"

#FILE
E3 = "ERROR:FILE PATH NOT FOUND"
E4 = "ERROR:NSE_DATA_DICT IS empty return"
E5 = "ERROR:ANGEL ONE CUSTOM CREATE JSON FILE NOT FOUND, PLEASE CHECK FILE NOT GENRATED FOR THAT DATE"
